name: Deploy to Cloudflare Pages

on:
  push:
    branches:
      - main
      - preview
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: fe8d6f5500462206277cad3450ab0eb9
          projectName: dream-board-mobile
          directory: .
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref_name }}
